<?php

use App\Controllers\AdminController;

$router->get('/admin', [AdminController::class, 'dashboard'], ['admin']);
$router->get('/admin/produse', [AdminController::class, 'products'], ['admin']);
$router->get('/admin/produse/verifica-disponibilitate', [AdminController::class, 'checkProductAvailability'], ['admin']);
$router->get('/admin/produse/creare', [AdminController::class, 'productForm'], ['admin']);
$router->get('/admin/produse/{id}/editare', [AdminController::class, 'productForm'], ['admin']);
$router->post('/admin/produse/salvare', [AdminController::class, 'saveProduct'], ['admin','csrf']);
$router->post('/admin/produse/{id}/salvare', [AdminController::class, 'saveProduct'], ['admin','csrf']);
$router->post('/admin/produse/{id}/arhivare', [AdminController::class, 'archiveProduct'], ['admin','csrf']);
$router->post('/admin/produse/genereaza-sku', [AdminController::class, 'generateMissingProductSkus'], ['admin','csrf']);
$router->post('/admin/produse/{id}/stergere', [AdminController::class, 'deleteProduct'], ['admin','csrf']);
$router->post('/admin/imagini/{id}/stergere', [AdminController::class, 'deleteImage'], ['admin','csrf']);
$router->get('/admin/categorii', [AdminController::class, 'categories'], ['admin']);
$router->get('/admin/categorii/creare', [AdminController::class, 'categoryForm'], ['admin']);
$router->get('/admin/categorii/{id}/editare', [AdminController::class, 'categoryForm'], ['admin']);
$router->post('/admin/categorii/salvare', [AdminController::class, 'saveCategory'], ['admin','csrf']);
$router->post('/admin/categorii/{id}/salvare', [AdminController::class, 'saveCategory'], ['admin','csrf']);
$router->post('/admin/categorii/{id}/vizibilitate', [AdminController::class, 'toggleCategoryVisibility'], ['admin','csrf']);
$router->post('/admin/categorii/{id}/stergere', [AdminController::class, 'deleteCategory'], ['admin','csrf']);
$router->get('/admin/comenzi', [AdminController::class, 'orders'], ['admin']);
$router->get('/admin/comenzi/export/csv', [AdminController::class, 'ordersCsv'], ['admin']);
$router->get('/admin/comenzi/export/pdf', [AdminController::class, 'ordersPdf'], ['admin']);
$router->get('/admin/comenzi/{id}', [AdminController::class, 'order'], ['admin']);
$router->post('/admin/comenzi/{id}', [AdminController::class, 'updateOrder'], ['admin','csrf']);
$router->post('/admin/comenzi/{id}/plata', [AdminController::class, 'updateOrderPayment'], ['admin','csrf']);
$router->get('/admin/clienti', [AdminController::class, 'customers'], ['admin']);
$router->get('/admin/clienti/{id}', [AdminController::class, 'customer'], ['admin']);
$router->get('/admin/recenzii', [AdminController::class, 'reviews'], ['admin']);
$router->post('/admin/recenzii/{id}', [AdminController::class, 'updateReview'], ['admin','csrf']);
$router->post('/admin/recenzii/{id}/stergere', [AdminController::class, 'deleteReview'], ['admin','csrf']);
$router->get('/admin/articole', [AdminController::class, 'posts'], ['admin']);
$router->get('/admin/articole/creare', [AdminController::class, 'postForm'], ['admin']);
$router->get('/admin/articole/{id}/editare', [AdminController::class, 'postForm'], ['admin']);
$router->post('/admin/articole/salvare', [AdminController::class, 'savePost'], ['admin','csrf']);
$router->post('/admin/articole/{id}/salvare', [AdminController::class, 'savePost'], ['admin','csrf']);
$router->get('/admin/newsletter', [AdminController::class, 'newsletter'], ['admin']);
$router->get('/admin/newsletter/export', [AdminController::class, 'newsletterCsv'], ['admin']);
$router->get('/admin/media', [AdminController::class, 'media'], ['admin']);
$router->post('/admin/media', [AdminController::class, 'uploadMedia'], ['admin','csrf']);
$router->get('/admin/setari', [AdminController::class, 'settings'], ['admin']);
$router->get('/admin/setari/email', [AdminController::class, 'emailSettings'], ['admin']);
$router->post('/admin/setari', [AdminController::class, 'saveSettings'], ['admin','csrf']);
$router->post('/admin/setari/email', [AdminController::class, 'saveEmailSettings'], ['admin','csrf']);
$router->post('/admin/setari/email/test', [AdminController::class, 'testEmail'], ['admin','csrf']);
$router->post('/admin/setari/plati/{key}', [AdminController::class, 'savePayment'], ['admin','csrf']);
